
import Header from "./header/page"
import Footer from "./footer/page"
import './module.page.css'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Flora Guajira',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Header/>

        {children}
      <Footer/>
      </body>
    </html>
  )
}
